### PR TITLE
fix: Register processes for cleanup

### LINKED ISSUE #152: Handle spawned child processes
Hey

We've encountered some issues running the flagger-k6-webhook deployment in a Kubernetes cluster.
After some time, the deployment has a lot of zombie processes, causing new forks/test executions to fail.
We've currently mitigated the issue by restarting the deployment, but it's not a long term solution for us.
We are also using the latest version of this project.

Some suggestions, after looking at other projects, is to use tini or dumb-init as an entrypoint, in order to reap the zombie processes.
Here's a ps output from the container running flagger-k6-webhook, after it has been running for 6 hours.
bild

### PR DESCRIPTION
**Pull request by zerok**
The idea here is to register k6 TestRuns, for which we do not want to wait for a result, with a cleanup routine so that no zombie processes stay around.

Right now the number of handler go-routines (those that wait for the TestRun processes) are limited in number. If that limit is reached, then the HTTP handler becomes blocking.

```[tasklist]
### Tasks
- [x] Make go-routine limit configurable
- [x] Test-cases for the process handlers
``` 

Resolves #152

### CODE REVIEW

File: pkg/handlers/launch.go [hunk 1]
```diff
@@ -144,23 +144,119 @@ type launchHandler struct {
...
-		kubeClient:      kubeClient,
-		slackClient:     slackClient,
-		lastFailureTime: make(map[string]time.Time),
-		sleep:           time.Sleep,
-	}, nil
+// registerProcessCleanup adds a handler to the process so that it will
+// eventually be closed and its resources returned.
+//
+// Note that this method can actually block which will, in turn, cause the
+// calling HTTP handler to be blocked.
```
Comment (iainlane) [inline pkg/handlers/launch.go:257]: hmm, that sounds like it might introduce regressions if we have people using this to launch a lot of tests. they might start seeing timeouts?

anything we can do about that? send a 429 back?

**Review by iainlane — COMMENTED** [review]
nice find!

main thing i'm wondering: what would happen if we didn't have the limit and instead updated the code to always `Wait()` but still allow any number of children to be launched? it'd remove the need for the pool. but perhaps it's not advisable ...

left comments with _not_ doing :point_up: in mind :slightly_smiling_face:

File: pkg/handlers/launch.go [hunk 2]
```diff
@@ -144,23 +144,119 @@ type launchHandler struct {
 	lastFailureTime      map[string]time.Time
 	lastFailureTimeMutex sync.Mutex
 
+	processToWaitFor       chan k6.TestRun
+	cancelWaitForProcesses context.CancelFunc
+	waitForProcessesDone   chan struct{}
+	ctx                    context.Context
```
[the remark this answers is not in the document]
Comment (zerok) [reply pkg/handlers/launch.go]: Unfortunately, I cannot completely get rid of struct-level context since that struct implements a http.Handler and I need the context outside of the request handler. I've limited its use now with https://github.com/grafana/flagger-k6-webhook/pull/153/commits/1decf4634aeda84e68af83d4ab0aebb4c272f7d8, though 🙂

File: pkg/handlers/launch.go [hunk 3]
```diff
@@ -254,7 +350,7 @@ func (h *launchHandler) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
 	}
 
 	cmdLog.Info("launching k6 test")
-	cmd, err := h.client.Start(payload.Metadata.Script, payload.Metadata.UploadToCloud, envVars, &buf)
+	cmd, err := h.client.Start(h.ctx, payload.Metadata.Script, payload.Metadata.UploadToCloud, envVars, &buf)
```
[the remark this answers is not in the document]
Comment (zerok) [reply pkg/handlers/launch.go:343]: Yes, I'm currently tempted to create a subcontext that is canceled when either the request context or the struct context is done.

File: pkg/handlers/launch.go [hunk 4]
```diff
@@ -268,13 +364,15 @@ func (h *launchHandler) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
 		logIfError(err)
 		logIfError(h.slackClient.AddFileToThreads(slackMessages, "k6-results.txt", buf.String()))
 		fail(fmt.Sprintf("error while waiting for test to start: %v", waitErr))
+		h.registerProcessCleanup(cmd)
```
[the remark this answers is not in the document]
Comment (zerok) [reply pkg/handlers/launch.go:357]: Not yet completely sure, but I think Cmd.Wait might not be thread-safe. Will try some things out, though.

File: pkg/handlers/launch.go (hunk 1 above)
Comment (zerok) [reply pkg/handlers/launch.go:247]: The problem right now is that the test is actually already running at this point. One thing I could do is basically request a token from the process-handler *before* the actual test starts to run. Not sure if its worth the effort, though.

File: pkg/handlers/launch.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (zerok) [reply pkg/handlers/launch.go]: Done with https://github.com/grafana/flagger-k6-webhook/pull/153/commits/6db6d989a3f4f07256901acd915009af69258f60 🙂

File: pkg/handlers/launch.go (hunk 1 above)
Comment (zerok) [reply pkg/handlers/launch.go:251]: Done. I've also exposed the number of still available concurrent tests as a metric.

File: cmd/main.go [hunk 5]
```diff
@@ -63,6 +65,11 @@ func run(args []string) error {
 			Value:   kubernetesClientNone,
 			Usage:   fmt.Sprintf("Kubernetes client to use: '%s' or '%s'", kubernetesClientInCluster, kubernetesClientNone),
 		},
+		&cli.IntFlag{
+			Name:    flagMaxProcessHandlers,
+			EnvVars: []string{"MAX_PROCESS_HANDLERS"},
```
[the remark this answers is not in the document]
Comment (zerok) [reply cmd/main.go]: Done :)

File: pkg/handlers/launch.go [hunk 6]
```diff
@@ -144,23 +144,119 @@ type launchHandler struct {
...
+	go func() {
+		<-ctx.Done()
+		close(h.processToWaitFor)
+		wg.Done()
+	}()
+	// We have a fixed number of available process handlers:
+	availableProcessHandlers := make(chan struct{}, maxProcessHandlers)
+	for i := 0; i < maxProcessHandlers; i++ {
+		availableProcessHandlers <- struct{}{}
+	}
```
[the remark this answers is not in the document]
Comment (zerok) [reply pkg/handlers/launch.go]: I've now replaced that part of the implementation to allow for "tokens" to be requested on the ServeHTTP level.

File: pkg/handlers/launch.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (zerok) [reply pkg/handlers/launch.go:381]: Solved by adding the maxConcurrentTests check around both paths.

File: pkg/handlers/launch.go [hunk 7]
```diff
@@ -214,6 +308,12 @@ func (h *launchHandler) buildEnvVars(payload *launchPayload) (map[string]string,
 }
 
 func (h *launchHandler) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
+	select {
+	case <-h.availableTestRuns:
+	default:
+		http.Error(resp, "Maximum concurrent test runs reached", 429)
```
Comment (iainlane) [inline pkg/handlers/launch.go:314]: just a micro readability nit :slightly_smiling_face: 

```suggestion
		http.Error(resp, "Maximum concurrent test runs reached", http.StatusTooManyRequests)
```

Comment (iainlane) [inline pkg/handlers/launch.go:314]: also, this would be interesting to log wouldn't it?

File: pkg/handlers/launch.go [hunk 8]
```diff
@@ -214,6 +308,12 @@ func (h *launchHandler) buildEnvVars(payload *launchPayload) (map[string]string,
 }
 
 func (h *launchHandler) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
```
Comment (iainlane) [inline pkg/handlers/launch.go:310]: can be for the next PR, but `ServeHTTP` is getting a bit chunky now, would be worth breaking it up to make the code easier to follow :-)

File: pkg/handlers/launch.go (hunk 7 above)
Comment (iainlane) [inline pkg/handlers/launch.go:314]: also², what do you think about setting `Retry-After` to a sensible value? hopefully flagger respects that ...

edit: checked and [it uses `retryablehttp`](https://github.com/fluxcd/flagger/blob/adc60596f5a1150d182bd5c3ad66dcd18ff796ea/pkg/controller/webhook.go#L50) which [does respect the header on a 429](https://github.com/hashicorp/go-retryablehttp/blob/1542b31176d3973a6ecbc06c05a2d0df89b59afb/client.go#L544-L566) :+1:

**Review by iainlane — COMMENTED** [review]
alright! thanks for the updates. I'm scared about using more goroutines but the best thing to do might be to try it out

just had a couple of comments on the 429

File: pkg/handlers/launch.go (hunk 7 above)
Comment (zerok) [reply pkg/handlers/launch.go]: hm... good point. I think going with something like 1 minutes should be useful in most scenarios. We could also go with something like the median of all wait-periods so far and even expose that through a histogram or something. Will take a look later :)

Comment (zerok) [reply pkg/handlers/launch.go]: will do :)

File: pkg/handlers/launch.go (hunk 8 above)
Comment (zerok) [reply pkg/handlers/launch.go:310]: Absolutely. That thing is a beast 🤣

File: pkg/handlers/launch.go (hunk 7 above)
Comment (zerok) [reply pkg/handlers/launch.go]: Done :) I now use the median from all previous execution times and fall back to one minute for the unlikely combination that the limit is reached but we don't have any values yet (e.g. the limit is 1 and we are currently in the first run)

**Review by iainlane — APPROVED** [review]
let's give it a go 👍

**Review by julienduchesne — APPROVED** [review]
